"use client";
import {useState,useEffect,useRef} from "react";
import {Dice5,Pin,Check,Copy,Code2,Compass,X,ExternalLink,LoaderCircle,GitBranch,Search,Download,ChevronRight,BookOpen,RefreshCw} from "lucide-react";
import {catalog,related,makeKit,type Concept,type Pin as Pinned} from "./ideas";
type Roll={ideas:Concept[];total:number;categories:string[];mode:string;message:string};
export default function Home(){
 const [view,setView]=useState("board"),[ideas,setIdeas]=useState<Concept[]>([]),[pins,setPins]=useState<Pinned[]>([]),[category,setCategory]=useState("Everything"),[categories,setCategories]=useState<string[]>([]),[query,setQuery]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[pinError,setPinError]=useState(""),[pinLoaded,setPinLoaded]=useState(false),[needsSignIn,setNeedsSignIn]=useState(false),[saving,setSaving]=useState(""),[selected,setSelected]=useState<Concept|null>(null),[detailTab,setDetailTab]=useState("idea"),[note,setNote]=useState(""),[platform,setPlatform]=useState("web app"),[copied,setCopied]=useState(""),[rolls,setRolls]=useState(0),[total,setTotal]=useState(0);
 const working=useRef(false),dialog=useRef<HTMLElement>(null);
 async function roll(nextCategory=category,nextQuery=query){if(working.current)return;working.current=true;setBusy(true);setError("");try{const r=await fetch("/api/roll",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({category:nextCategory,query:nextQuery,exclude:ideas.map(i=>i.id)})});const d=await r.json() as Roll & {error?:string};if(!r.ok)throw new Error(d.error);setIdeas(d.ideas);setTotal(d.total);setCategories(d.categories);setRolls(x=>x+1);setView("board");}catch(e){setError(e instanceof Error?e.message:"Could not roll ideas.")}finally{setBusy(false);working.current=false}}
 async function loadPins(){setPinError("");try{const r=await fetch("/api/pins");const d=await r.json() as {pins:Pinned[];error?:string};if(r.status===401){setNeedsSignIn(true);return}if(!r.ok)throw new Error(d.error);setPins(d.pins);setPinLoaded(true);setNeedsSignIn(false);}catch(e){setPinError(e instanceof Error?e.message:"Could not load pins.")}}
 useEffect(()=>{roll();loadPins()},[]);
 function open(idea:Concept,tab="idea"){setSelected(idea);setNote(pins.find(p=>p.idea.id===idea.id)?.note||"");setDetailTab(tab);setCopied("")}
 async function savePin(idea:Concept,remove=false,notes=""){if(saving||!pinLoaded)return;setSaving(idea.id);setPinError("");try{const r=await fetch("/api/pins"+(remove?"?id="+encodeURIComponent(idea.id):""),remove?{method:"DELETE"}:{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idea,note:notes})});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setPins(p=>remove?p.filter(x=>x.idea.id!==idea.id):[{idea,note:notes,createdAt:p.find(x=>x.idea.id===idea.id)?.createdAt||new Date().toISOString()},...p.filter(x=>x.idea.id!==idea.id)]);}catch(e){setPinError(e instanceof Error?e.message:"Could not save pin.");}finally{setSaving("")}}
 function toggle(idea:Concept){const existing=pins.find(p=>p.idea.id===idea.id);savePin(idea,!!existing,existing?.note||"")}
 useEffect(()=>{if(!selected)return;const previous=document.activeElement as HTMLElement;const old=document.body.style.overflow;document.body.style.overflow="hidden";dialog.current?.querySelector<HTMLButtonElement>("button")?.focus();function key(e:KeyboardEvent){if(e.key==="Escape")setSelected(null);if(e.key==="Tab"){const all=dialog.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],summary,textarea,select,input');if(!all?.length)return;const first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}window.addEventListener("keydown",key);return()=>{window.removeEventListener("keydown",key);document.body.style.overflow=old;previous?.focus()}},[selected]);
 const kit=selected?makeKit(selected,platform,note):null;
 async function copy(text:string,id:string){try{await navigator.clipboard.writeText(text);setCopied(id);setTimeout(()=>setCopied(""),2000)}catch{setError("Clipboard unavailable. Use Download kit instead.")}}
 function download(){if(!kit||!selected)return;const url=URL.createObjectURL(new Blob([kit.text],{type:"text/plain"}));const a=document.createElement("a");a.href=url;a.download=selected.id+"-codex-kit.txt";a.click();URL.revokeObjectURL(url)}
 const visible=view==="pins"?pins.map(p=>p.idea):ideas;
 return <div className="shell"><aside className="sidebar"><a className="brand" href="/"><b>m</b>muse<span>.</span></a><div className="side-label">A HOME FOR YOUR NEXT WHAT IF</div><nav aria-label="Main">{[["board","Explore",Compass],["pins","Pinned ideas",Pin],["about","How it works",BookOpen]].map(([id,label,Icon]:any)=><button className={view===id?"nav active":"nav"} key={id} aria-label={label} onClick={()=>setView(id)}><Icon size={19}/><span>{label}</span>{id==="pins"&&<small>{pins.length}</small>}</button>)}</nav><div className="side-bottom"><Dice5 size={26}/><strong>Follow a spark.<br/>See where it goes.</strong><p>Play with directions. Keep the good ones. Build when you're ready.</p><small>YOUR PRIVATE BRAINSTORMING ROOM</small></div></aside>
 <main><header><span>Muse <i>/</i> <strong>{view==="pins"?"Pinned ideas":view==="about"?"How it works":"Brainstorming room"}</strong></span><span className="badge">Private to you</span></header><div className="workspace">
 {view==="board"&&<><div className="heading"><div><div className="eyebrow">A LITTLE CURIOSITY GOES A LONG WAY</div><h1>What if you built <em>something different?</em></h1><p>Roll for a spark. Explore a few paths. Keep what catches your eye.</p></div><div className="dice-stamp"><Dice5 size={38}/><small>ROLL {String(rolls).padStart(2,"0")}</small></div></div>
 <section className="brainstorm-controls"><div className="controltop"><div><span className="eyebrow">FOLLOW YOUR CURIOSITY</span><h2>Leave the direction open.</h2></div><button className="primary rollbutton" disabled={busy} onClick={()=>roll()}>{busy?<LoaderCircle className="spin" size={20}/>:<Dice5 size={20}/>} {busy?"Rolling...":"Roll the dice"}</button></div><div className="category-row">{["Everything",...categories].map(c=><button key={c} disabled={busy} className={category===c?"category selected":"category"} onClick={()=>{setCategory(c);roll(c)}}>{c}</button>)}</div><form className="library-search" onSubmit={e=>{e.preventDefault();roll()}}><Search size={16}/><input aria-label="Search the research library" value={query} onChange={e=>setQuery(e.target.value)} maxLength={80} placeholder="Or follow a topic in the research library, like solitaire"/><button disabled={busy}>Explore topic</button></form></section>
 <div className="mode-note"><BookOpen size={16}/><span><strong>Research library mode.</strong> Rolls explore {total} matching concepts. Open-ended AI and automatic Reddit discovery are not connected yet.</span></div></>}
 {view==="pins"&&<div className="heading"><div><div className="eyebrow">SOME SPARKS ARE WORTH KEEPING</div><h1>Your <em>pinned ideas.</em></h1><p>Pick up a thread, add your own notes, or turn it into a first build.</p></div></div>}
 {(error||pinError)&&<div className="notice" role="alert">{error||pinError}{pinError&&<button className="inline-retry" onClick={loadPins}><RefreshCw size={14}/>Retry pins</button>}</div>}
 {needsSignIn&&<div className="notice">Sign in to save and revisit pins. <a href="/signin-with-chatgpt?return_to=/" target="_top">Sign in with ChatGPT</a></div>}
 {view!=="about"&&<><div className="resultshead"><div><h2>{view==="pins"?"Your collection":"Today's possible paths"} <small>{visible.length}</small></h2><p>{view==="pins"?"Saved with your account, including the concept and your notes.":"Creative hypotheses inspired by public conversations."}</p></div>{view==="board"&&<span className="small-label">PIN FIRST. DECIDE LATER.</span>}</div>
 <div className="cards">{visible.map((idea,i)=>{const pinned=pins.some(p=>p.idea.id===idea.id);return <article className={"card brainstorm-card tone-"+idea.category.toLowerCase().split(" ")[0]} key={idea.id}><div className="cardtop"><span>{String(i+1).padStart(2,"0")}</span><span>{idea.category}</span><button className={pinned?"pinbutton pinned":"pinbutton"} title={pinned?"Unpin idea":"Pin for later"} aria-label={(pinned?"Unpin ":"Pin ")+idea.name} aria-pressed={pinned} disabled={!pinLoaded||!!saving} onClick={()=>toggle(idea)}>{saving===idea.id?<LoaderCircle size={17} className="spin"/>:<Pin size={17}/>}</button></div><h3>{idea.name}</h3><p>{idea.pitch}</p><div className="twist"><GitBranch size={15}/><span>{idea.twist}</span></div><div className="tags"><span>{idea.effort}</span><span>{idea.sources.length} source threads</span></div>{view==="pins"&&pins.find(p=>p.idea.id===idea.id)?.note&&<p className="saved-note">Your note: {pins.find(p=>p.idea.id===idea.id)?.note}</p>}<div className="cardfooter"><button className="card-kit" onClick={()=>open(idea,"kit")}><Code2 size={15}/>Codex kit</button><button onClick={()=>open(idea)}>Explore paths<ChevronRight size={16}/></button></div></article>})}</div>
 {!visible.length&&<div className="empty">{busy?<LoaderCircle size={30} className="spin"/>:<Pin size={30}/>}<h3>{busy?"Finding a few directions...":view==="pins"?"Your next good idea can live here.":"No concepts in this part of the library yet."}</h3><p>{view==="pins"?"Pin an idea from Explore to return to it later.":"Try a broader topic or clear your search. Custom AI brainstorming awaits its connection."}</p><button className="secondary" onClick={()=>{setView("board");setQuery("");setCategory("Everything");roll("Everything","")}}>Explore ideas</button></div>}
 <div className="footnote"><GitBranch size={16}/><span>Keep the observation and the invention separate. Sources inspire these ideas; uniqueness and demand still need research.</span></div></>}
 {view==="about"&&<section className="method"><div className="eyebrow">ROLL. EXPLORE. PIN. BUILD.</div><h2>A room for ideas, before they become projects.</h2><ol><li><strong>Roll for a direction</strong><p>Explore a curated research library of {catalog.length} concepts across games, everyday life, tools, community, hobbies, creativity, and learning. A roll shuffles available concepts, prefers ones absent from your current board, and mixes categories when you explore Everything. It does not run an AI model or scan Reddit live.</p></li><li><strong>Follow different paths</strong><p>Open a concept to see related variations, a distinctive mechanic, the first three features, and public discussions that inspired it. The source observations were researched on October 6, 2026. The concepts are creative proposals, not requests literally made by the people in those threads.</p></li><li><strong>Pin for later</strong><p>Your pins and notes are stored with your signed-in account. A successful pin saves the whole concept snapshot so it remains useful later. Failed saves stay visible and can be retried.</p></li><li><strong>Make a Codex kit</strong><p>Choose a web app or Unity prototype, add your own direction, and copy the opening prompt. The workflow breaks the build into a vertical slice, distinctive mechanic, completed MVP, testing, and feedback. Download both together when you want to start.</p></li><li><strong>Keep discovery honest</strong><p>AI brainstorming and automatic Reddit discovery still need their connections. For now the library is finite. Existing competitors appear in several source discussions, so research alternatives before claiming a concept is unique.</p></li></ol></section>}
 <footer>muse<span>.</span><small>Curiosity, with somewhere to go.</small><small className="footer-right">BRAINSTORMING ROOM / V2</small></footer></div></main>
 {selected&&kit&&<div className="overlay" onClick={()=>setSelected(null)}><section ref={dialog} className="detail wide-detail" role="dialog" aria-modal="true" aria-labelledby="detail-title" onClick={e=>e.stopPropagation()}><div className="detailtop"><span className="eyebrow">{selected.category.toUpperCase()} / A POSSIBLE PATH</span><button aria-label="Close idea" onClick={()=>setSelected(null)}><X size={22}/></button></div><h2 id="detail-title">{selected.name}</h2><p className="lead">{selected.pitch}</p><div className="detail-tabs" role="tablist" aria-label="Idea details"><button role="tab" aria-selected={detailTab==="idea"} onClick={()=>setDetailTab("idea")}><GitBranch size={16}/>Explore the idea</button><button role="tab" aria-selected={detailTab==="kit"} onClick={()=>setDetailTab("kit")}><Code2 size={16}/>Codex build kit</button></div>
 {detailTab==="idea"?<><div className="twist detail-twist"><GitBranch size={20}/><span><strong>The twist</strong>{selected.twist}</span></div><h3>Other paths from the same spark</h3><div className="path-options">{related(selected).map(v=><button key={v.id} onClick={()=>open(v)}><span>{v.name}</span><small>{v.twist}</small><ChevronRight size={17}/></button>)}</div><h3>Who might enjoy it</h3><p>{selected.audience}</p><h3>The first useful version</h3><ul>{selected.features.map(f=><li key={f}>{f}</li>)}</ul><h3>What the discussions actually say</h3><div className="detailsources">{selected.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noreferrer"><span>Reddit / research snapshot / {selected.researchedAt}</span><strong>{s.title} <ExternalLink size={14}/></strong><p>{s.observation}</p></a>)}</div><h3>Before you invest in it</h3><p>{selected.validation}</p><div className="actions"><button className="primary" disabled={!pinLoaded||!!saving} onClick={()=>savePin(selected,pins.some(p=>p.idea.id===selected.id),note)}><Pin size={17}/>{pins.some(p=>p.idea.id===selected.id)?"Unpin idea":"Pin for later"}</button><button className="secondary" onClick={()=>setDetailTab("kit")}><Code2 size={17}/>Make a Codex kit</button></div></>:<><div className="kit-settings"><label>Build as<select value={platform} onChange={e=>setPlatform(e.target.value)}><option value="web app">Web app</option><option value="desktop tool">Desktop tool</option><option value="Unity game prototype">Unity game prototype</option></select></label><label>Your direction<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} placeholder="For example: focus on offline play, a moody space theme, and one simple ruleset."/></label><button className="secondary" disabled={!pinLoaded||!!saving} onClick={()=>savePin(selected,false,note)}><Pin size={15}/>{saving===selected.id?"Saving...":pins.some(p=>p.idea.id===selected.id)?"Save notes to pin":"Pin idea and notes"}</button></div><h3>Opening prompt</h3><p>Paste this into a new Codex task to start the first version.</p><pre className="prompt-preview">{kit.prompt}</pre><button className="primary" onClick={()=>copy(kit.prompt,"prompt")}>{copied==="prompt"?<Check size={17}/>:<Copy size={17}/>} {copied==="prompt"?"Copied":"Copy opening prompt"}</button><h3>Your build workflow</h3><div className="workflow">{kit.workflow.map(w=><details key={w.title}><summary>{w.title}</summary><p>{w.task}</p><button className="text-button" onClick={()=>copy(w.task,w.title)}><Copy size={14}/>{copied===w.title?"Copied":"Copy this step"}</button></details>)}</div><div className="actions"><button className="secondary" onClick={()=>copy(kit.text,"all")}><Copy size={16}/>{copied==="all"?"Copied":"Copy complete kit"}</button><button className="secondary" onClick={download}><Download size={16}/>Download kit</button></div></>}
 {pinError&&<div className="notice" role="alert">{pinError}</div>}<p className="disclaimer">Research library concept. Originality, demand, and build effort are hypotheses.</p></section></div>}
 </div>
}

